server:
  port: 8080
  address: localhost
  servlet:
    context-path: /api




spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colors?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
